"""Deterministic source emission for ``src/peripherals.cpp``.

The C++ file is a pure function of the project's ``[[peripherals]]``
list.  Re-running ``alloy add`` on the same configuration twice
SHALL produce byte-identical output.
"""

from __future__ import annotations

from pathlib import Path

from alloy_cli import __version__ as _alloy_cli_version
from alloy_cli.core.project import PeripheralEntry, ProjectConfig

_DO_NOT_EDIT_BANNER = (
    "// SPDX-License-Identifier: MIT OR Apache-2.0\n"
    "//\n"
    "// AUTO-GENERATED by alloy-cli — do not edit by hand.\n"
    "// To change this file, edit alloy.toml and re-run `alloy add` /\n"
    "// `alloy build`.  The contents are a pure function of the [[peripherals]]\n"
    "// table; running alloy-cli twice produces byte-identical output.\n"
    "\n"
)


def _format_uart(entry: PeripheralEntry) -> str:
    p = entry.payload
    pieces = [
        f"// {entry.name}: {p.get('peripheral', '')}",
        f"//   tx={p.get('tx', '?')}  rx={p.get('rx', '?')}  baud={p.get('baud', 115200)}",
        f"alloy::Uart {entry.name}{{ /* peripheral={p.get('peripheral', '?')} */ }};",
        "",
    ]
    return "\n".join(pieces)


def _format_gpio(entry: PeripheralEntry) -> str:
    p = entry.payload
    pieces = [
        f"// {entry.name}: pin={p.get('pin', '?')}  mode={p.get('mode', '?')}",
        f"alloy::Gpio {entry.name}{{ /* pin={p.get('pin', '?')} */ }};",
        "",
    ]
    return "\n".join(pieces)


def _format_spi(entry: PeripheralEntry) -> str:
    p = entry.payload
    pieces = [
        f"// {entry.name}: {p.get('peripheral', '')}",
        f"//   sck={p.get('sck', '?')}  miso={p.get('miso', '?')}  mosi={p.get('mosi', '?')}",
        f"alloy::Spi {entry.name}{{ /* peripheral={p.get('peripheral', '?')} */ }};",
        "",
    ]
    return "\n".join(pieces)


def _format_i2c(entry: PeripheralEntry) -> str:
    p = entry.payload
    pieces = [
        f"// {entry.name}: {p.get('peripheral', '')}",
        f"//   sda={p.get('sda', '?')}  scl={p.get('scl', '?')}",
        f"alloy::I2c {entry.name}{{ /* peripheral={p.get('peripheral', '?')} */ }};",
        "",
    ]
    return "\n".join(pieces)


def _format_generic(entry: PeripheralEntry) -> str:
    p = entry.payload
    extras = ", ".join(f"{k}={p[k]!r}" for k in sorted(p) if k not in {"kind", "name"})
    pieces = [
        f"// {entry.name} (kind={entry.kind}): {extras}",
        f"// alloy-cli does not yet emit a typed handle for kind={entry.kind!r}.",
        f"alloy::Peripheral {entry.name};  // generic handle",
        "",
    ]
    return "\n".join(pieces)


_EMITTERS = {
    "uart": _format_uart,
    "gpio": _format_gpio,
    "spi": _format_spi,
    "i2c": _format_i2c,
}


def peripherals_cpp(config: ProjectConfig) -> str:
    """Return the deterministic contents of ``src/peripherals.cpp``."""
    parts: list[str] = [
        _DO_NOT_EDIT_BANNER,
        f'// alloy-cli {_alloy_cli_version} — project "{config.project.name}"\n',
        "\n",
        '#include "alloy/peripherals.hpp"\n',
        "\n",
        "namespace app {\n",
        "\n",
    ]
    for entry in config.peripherals:
        emitter = _EMITTERS.get(entry.kind, _format_generic)
        parts.append(emitter(entry))
    parts.append("} // namespace app\n")
    return "".join(parts)


def emit_targets(config: ProjectConfig) -> dict[Path, str]:
    """Map relative target path → file contents for the source emit step."""
    return {Path("src/peripherals.cpp"): peripherals_cpp(config)}


__all__ = ["emit_targets", "peripherals_cpp"]
