"""Regression guard: every internal link in the rendered site resolves.

Walks `site/**/*.html`, parses every `<a href="...">`, and resolves
each internal target.  Skips external `http(s)://` and `mailto:`
URLs.  Asserts every internal anchor resolves to a real file (or
in-page anchor).

Strict-mode `mkdocs build` already catches link warnings during
the build, but it can miss links that are generated by
mkdocs-redirects, mkdocstrings, or mkdocs-click — those land in
the rendered HTML AFTER mkdocs's own checks run.

Marked ``@pytest.mark.docs`` so contributors who haven't installed
``pip install -e .[docs]`` get a SKIP rather than an import-error.
"""

from __future__ import annotations

import html.parser
import os
import shutil
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlparse

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
MKDOCS_YML = REPO_ROOT / "mkdocs.yml"


pytestmark = pytest.mark.docs


def _mkdocs_available() -> bool:
    return shutil.which("mkdocs") is not None


class _LinkExtractor(html.parser.HTMLParser):
    """Collect every `<a href="...">` in a page."""

    def __init__(self) -> None:
        super().__init__()
        self.links: list[str] = []

    def handle_starttag(
        self, tag: str, attrs: list[tuple[str, str | None]]
    ) -> None:
        if tag.lower() != "a":
            return
        for name, value in attrs:
            if name.lower() == "href" and value:
                self.links.append(value)


def _build_site(tmp_path: Path) -> Path:
    site_dir = tmp_path / "site"
    env = {**os.environ, "DISABLE_MKDOCS_2_WARNING": "true"}
    subprocess.run(
        [
            sys.executable,
            "-m",
            "mkdocs",
            "build",
            "--strict",
            "--config-file",
            str(MKDOCS_YML),
            "--site-dir",
            str(site_dir),
        ],
        cwd=REPO_ROOT,
        env=env,
        check=True,
        capture_output=True,
        timeout=120,
    )
    return site_dir


@pytest.mark.skipif(
    not _mkdocs_available(),
    reason="`mkdocs` not installed; run `pip install -e .[docs]`",
)
def test_every_internal_link_resolves(tmp_path: Path) -> None:
    """Every `<a href>` whose target is internal SHALL resolve."""
    site_dir = _build_site(tmp_path)
    html_files = list(site_dir.rglob("*.html"))
    assert html_files, "build produced no HTML files"

    broken: list[str] = []
    for page in html_files:
        # Skip the 404 page — Material renders it with site-absolute
        # links (`/alloy-cli/...`) that only resolve at deploy time,
        # not against the local filesystem.
        if page.name == "404.html":
            continue
        text = page.read_text(encoding="utf-8")
        extractor = _LinkExtractor()
        extractor.feed(text)
        for href in extractor.links:
            if _is_external(href):
                continue
            if href.startswith("#"):
                continue  # in-page anchor — assume Material handles it
            if href.startswith("/"):
                continue  # site-absolute (Material chrome) — deploy-time
            target_path, _, _ = href.partition("#")
            if not target_path:
                continue
            # Skip intentional GitHub-rendered paths to repo-root
            # neighbours (`../src/...`, `../schema/...`,
            # `../data/...`, `../tests/...`, `../pyproject.toml`,
            # `../openspec/...`).  These docs are read on github.com
            # too; the relative path resolves there even though
            # mkdocs can't follow it.
            if any(
                target_path.startswith(prefix)
                for prefix in (
                    "../src/",
                    "../schema/",
                    "../data/",
                    "../tests/",
                    "../scripts/",
                    "../openspec/",
                    "../pyproject.toml",
                    "../README.md",
                )
            ):
                continue
            resolved = (page.parent / target_path).resolve()
            # Targets are usually `<dir>/` → `<dir>/index.html`.
            if resolved.is_dir():
                resolved = resolved / "index.html"
            if not resolved.exists():
                rel_target = (
                    resolved.relative_to(site_dir)
                    if resolved.is_relative_to(site_dir)
                    else resolved
                )
                broken.append(
                    f"  • {page.relative_to(site_dir)} → {href} "
                    f"(resolved: {rel_target})"
                )

    assert not broken, (
        "Broken internal links in the rendered site:\n"
        + "\n".join(broken[:30])
        + (f"\n  … and {len(broken) - 30} more" if len(broken) > 30 else "")
    )


def _is_external(href: str) -> bool:
    """True for absolute http(s):// + mailto: + javascript: URLs."""
    parsed = urlparse(href)
    if parsed.scheme in ("http", "https", "mailto", "ftp", "javascript", "tel"):
        return True
    return False
